# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creatorEmail', models.TextField()),
                ('followingEmail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FundUpdateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.TextField()),
                ('newFund', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fund', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='MirrorForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creatorEmail', models.TextField()),
                ('mirroringEmail', models.TextField()),
                ('fund', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='SignupForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('firstName', models.TextField()),
                ('middleName', models.TextField()),
                ('lastName', models.TextField()),
                ('ssn', models.DecimalField(decimal_places=0, max_digits=9)),
                ('zipCode', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StockInvestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('creatorEmail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('isFromMirror', models.BooleanField(default=False)),
                ('mirrorSold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('middleName', models.TextField()),
                ('lastName', models.TextField()),
                ('ssn', models.DecimalField(decimal_places=0, max_digits=9)),
                ('fund', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('zipCode', models.DecimalField(decimal_places=0, max_digits=5)),
                ('UserData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_creator_set', to='account.UserAccount'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='mirrorEntry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mirror_set', to='account.StockRecord'),
        ),
        migrations.AddField(
            model_name='mirror',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_creator_set', to='account.UserAccount'),
        ),
        migrations.AddField(
            model_name='mirror',
            name='mirroring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_set', to='account.UserAccount'),
        ),
        migrations.AddField(
            model_name='follow',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_creator_set', to='account.UserAccount'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_set', to='account.UserAccount'),
        ),
    ]
